version: "3.9"
services:
  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
      - .:/config
    ports:
      # HTTP server
      - 7000:7000
