[sources.demo_logs]
type                    = "demo_logs"
format                  = "json"

[sinks.console]
type                    = "console"
inputs                  = ["demo_logs"]
target                  = "stdout"

[sinks.console.encoding]
codec                   = "json"